### ISSUE TITLE
[ui] Designer font display

### ISSUE THREAD

**Issue by Jmm233** [pmd/pmd-designer#10]
PMD designer v6.11.0

OS:Ubuntu16.04

![2019-02-24 17-35-42](https://user-images.githubusercontent.com/39986242/53297527-b1a36b80-385a-11e9-993a-dd0ff1e33ed0.png)

The font in the designer is too difficult to read,so i come for help.
thank you

**Comment by ChitsuthaCSKKU** [comment]
<img width="1440" alt="Screen Shot 2563-12-09 at 14 52 50" src="https://user-images.githubusercontent.com/46390758/101638438-5beb8380-3a2e-11eb-8abe-6bc2dfcbdb34.png">

I ran the designer from run.sh designer on macOS. Anyone knows how to solve this? Thanks

**Comment by adangel** [comment]
@ChitsuthaCSKKU Which java version and openjfx version are you using? Try updating to the latest version, maybe that solves the problem.

**Comment by ChitsuthaCSKKU** [comment]
I am using 
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9)
OpenJDK 64-Bit Server VM (build 15.0.1+9, mixed mode, sharing)
javafx-sdk-11.0.2

which are the latest version, I think?

**Comment by savithraj** [comment]
I used openjfx version 16 but I am getting below error. If I use version 11 then I am getting the same UI as @ChitsuthaCSKKU

`Jun 03, 2021 8:54:29 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @40f9161a'
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:261)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:286)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:160)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:273)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:286)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:160)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:831)`

**Comment by oowekyala** [comment]
@savithraj Have you had a look at #49? It looks similar to your error

**Comment by jsotuyod** [comment]
I did some research into this, and the original issue seems to be rooted on the overall way the javafx renderer works on Linux, which effectively produces blurry text (ie: look into https://github.com/woky/javafx-hates-linux).

Fortunately, it seems that simply setting:

```java
System.setProperty("prism.text", "t2k");
System.setProperty("prism.lcdtext", "true");
```

is enough to get much better results. Moreover, this can be done during application startup (in the `DesignerStarter`) with no further changes needed in the application.

I'm unsure if these flags have any unwanted effect on other platforms (that is, f we should only set this when detecting we run under Linux).

**Comment by jsotuyod** [comment]
As for the issue on Mac shown on https://github.com/pmd/pmd-designer/issues/10#issuecomment-741786111 I was able to reproduce it using an older version of javafx.

When I run from the IDE (using Javafx 11) the text shows corrupted. Doing some trials I found out that JavaFX 14+ is needed to fix this.
