### ISSUE TITLE
Designer won't start on macOS 11.3 (M1)

### ISSUE THREAD

**Issue by jonathanwiesel** [pmd/pmd-designer#49]
**Describe the bug**
Running the designer fails with the following output
(sorry if this is a dumb question, I couldn't find anything related to it and I'm not familiar with it)

```
run.sh designer                                                                    
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:831)
```
 
**Additional context**
 - OS: macOS 11.3, Macbook Air M1 2020
 - Java: 
 ```
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment (build 16+14)
OpenJDK 64-Bit Server VM (build 16+14, mixed mode)
```
- JavaFX: 16 (although also tried with 11.0.2)

**Comment by oowekyala** [comment]
I don't think the designer supports openjfx >= 13. I haven't tested that in a while though... You'll probably need to try with javafx 11, but AFAIK you'll also need a Java 11 runtime, not java 16.

**Comment by jonathanwiesel** [comment]
Thank you for the quick response @oowekyala, I've downgraded to Java 11 (11.0.10+9) and JavaFX 11.0.2 but unfortunately the problem persists

**Comment by oowekyala** [comment]
Then I suspect this is a problem with your javafx version.. [This ticket](https://github.com/openjfx/openjfx-docs/issues/69) has a similar error, they hadn't installed the MacOs version, maybe it can help you. I can't test your setup as I don't have a mac...

**Comment by jonathanwiesel** [comment]
Actually I came across [this](https://gluonhq.com/javafx-for-apple-m1/) it seems that I needed the latest javafx 17 release that is compiled for Apple ARM architecture.

Thanks for the support @oowekyala

**Comment by rsoesemann** [comment]
@jonathanwiesel did you actually get the Rule Designer running on your Macbook. I have an M1 Macbook Pro and cant solve it. Any way you could help me?
