### ISSUE TITLE
NPE when launching Designer

### ISSUE THREAD

**Issue by armorcodehemant** [pmd/pmd-designer#72]
**Describe the bug**

```
./pmd designer
[main] INFO net.sourceforge.pmd.cli.commands.internal.AbstractPmdSubcommand - Log level is at INFO
java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at net.sourceforge.pmd.util.fxdesigner.DesignerStarter.getJavaFxVersion(DesignerStarter.java:116)
	at net.sourceforge.pmd.util.fxdesigner.DesignerStarter.isCompatibleJavaFxVersion(DesignerStarter.java:100)
	at net.sourceforge.pmd.util.fxdesigner.DesignerStarter.launchGui(DesignerStarter.java:153)
	at net.sourceforge.pmd.cli.commands.internal.DesignerCommand.execute(DesignerCommand.java:28)
	at net.sourceforge.pmd.cli.commands.internal.AbstractPmdSubcommand.call(AbstractPmdSubcommand.java:35)
	at net.sourceforge.pmd.cli.commands.internal.AbstractPmdSubcommand.call(AbstractPmdSubcommand.java:20)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at net.sourceforge.pmd.cli.PmdCli.main(PmdCli.java:18)
```

**Version**:
7.0.0-rc3 

**To Reproduce**
run command "pmd designer"

**Desktop:**
 - Mac OS: 13.4 (22F66)
 - Java: java version : "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)

JavaFx:
javafx.runtime.version=8.0.291
javafx.runtime.build=b09

**Comment by adangel** [comment]
Thanks for the report. We are searching for "javafx.properties", but can't find it: https://github.com/pmd/pmd-designer/blob/64b89c6ac0d1e434122d344ec0e45b7b8a9823c5/src/main/java/net/sourceforge/pmd/util/fxdesigner/DesignerStarter.java#L81

There are two problems here:
* we should handle the case, that we can't find the file (and `getResourceAsStream()` returns `null`
* we don't account for the oracle java8 directory structure, where this property file is not in `lib` but in `jre/lib/`. We make this assumption here: https://github.com/pmd/pmd/blob/512d6cbb8d198119a588b84c238ed78d75abda0c/pmd-dist/src/main/resources/scripts/pmd#L177-L178 - here we only deal with openjfx, but the java8 case is missing.

**Comment by adangel** [comment]
To get it running for you, try to use a newer java version and openjfx. You need to set the env var `JAVAFX_HOME` then (see https://docs.pmd-code.org/latest/pmd_userdocs_extending_designer_reference.html).

Since you are using MacOS, you probably anyway need to use a newer javafx version... (#10, #49).

**Comment by adangel** [comment]
In summary: Oracle Java8 contains an embedded version of javafx - so our start script can't add the jre/lib or lib folder onto the classpath (and it shouldn't - we would try to modify the boot classpath). So, we need to live with the fact, that javafx.properties can't be found on the classpath. That means, we don't need to change the start script on PMD side.

But we can search this file in a different way - an this at least works for me under Linux (don't have a MacOS machine to test).

We basically look, from where the javafx classes have been loaded (protection domain, code source) and try to guess where the javafx.properties is.
See #76.
